package com.graciano.archbank.security;

import com.auth0.jwt.JWT;
import com.auth0.jwt.algorithms.Algorithm;
import com.auth0.jwt.interfaces.DecodedJWT;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.security.core.authority.AuthorityUtils;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.test.util.ReflectionTestUtils;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Collections;

import static org.junit.jupiter.api.Assertions.*;

class JwtTokenServiceTest {

    private static final String SECRET = "test-secret-key-for-unit-tests";
    private static final String ISSUER = "ArchBank";

    private JwtTokenService jwtTokenService;

    @BeforeEach
    void setUp() {
        jwtTokenService = new JwtTokenService();
        ReflectionTestUtils.setField(jwtTokenService, "secret", SECRET);
        jwtTokenService.init();
    }

    @Test
    @DisplayName("Should generate a token with correct subject, issuer and expiration")
    void shouldGenerateTokenWithCorrectClaims() {
        UserDetails userDetails = buildUserDetails("test@email.com");

        String token = jwtTokenService.generateToken(userDetails);
        assertNotNull(token);

        DecodedJWT decoded = JWT.require(Algorithm.HMAC256(SECRET))
                .withIssuer(ISSUER)
                .build()
                .verify(token);

        assertEquals("test@email.com", decoded.getSubject());
        assertEquals(ISSUER, decoded.getIssuer());
        assertNotNull(decoded.getIssuedAt());
        assertNotNull(decoded.getExpiresAt());

        long validitySeconds = (decoded.getExpiresAt().getTime() - decoded.getIssuedAt().getTime()) / 1000;
        assertEquals(thirtyMinutesInSeconds(), validitySeconds);
    }

    @Test
    @DisplayName("Should validate a token generated by the service successfully")
    void shouldValidateTokenSuccessfully() {
        UserDetails userDetails = buildUserDetails("test@email.com");
        String token = jwtTokenService.generateToken(userDetails);

        DecodedJWT result = jwtTokenService.validateToken(token);

        assertNotNull(result);
        assertEquals("test@email.com", result.getSubject());
    }

    @Test
    @DisplayName("Should return null when token is malformed")
    void shouldReturnNullWhenTokenIsMalformed() {
        DecodedJWT result = jwtTokenService.validateToken("this-is-not-a-valid-jwt");

        assertNull(result);
    }

    @Test
    @DisplayName("Should return null when token signature does not match the secret")
    void shouldReturnNullWhenSignatureIsInvalid() {
        String tokenSignedWithDifferentSecret = JWT.create()
                .withSubject("test@email.com")
                .withIssuer(ISSUER)
                .withIssuedAt(Instant.now())
                .withExpiresAt(Instant.now().plus(30, ChronoUnit.MINUTES))
                .sign(Algorithm.HMAC256("a-completely-different-secret"));

        DecodedJWT result = jwtTokenService.validateToken(tokenSignedWithDifferentSecret);

        assertNull(result);
    }

    @Test
    @DisplayName("Should return null when token is expired")
    void shouldReturnNullWhenTokenIsExpired() {
        String expiredToken = JWT.create()
                .withSubject("test@email.com")
                .withIssuer(ISSUER)
                .withIssuedAt(Instant.now().minus(1, ChronoUnit.HOURS))
                .withExpiresAt(Instant.now().minus(30, ChronoUnit.MINUTES))
                .sign(Algorithm.HMAC256(SECRET));

        DecodedJWT result = jwtTokenService.validateToken(expiredToken);

        assertNull(result);
    }

    @Test
    @DisplayName("Should return null when token issuer does not match")
    void shouldReturnNullWhenIssuerIsInvalid() {
        String tokenWithWrongIssuer = JWT.create()
                .withSubject("test@email.com")
                .withIssuer("SomeOtherIssuer")
                .withIssuedAt(Instant.now())
                .withExpiresAt(Instant.now().plus(30, ChronoUnit.MINUTES))
                .sign(Algorithm.HMAC256(SECRET));

        DecodedJWT result = jwtTokenService.validateToken(tokenWithWrongIssuer);

        assertNull(result);
    }

    @Test
    @DisplayName("Should extract the email (subject) from a decoded token")
    void shouldExtractEmailFromDecodedToken() {
        UserDetails userDetails = buildUserDetails("extract-me@email.com");
        String token = jwtTokenService.generateToken(userDetails);
        DecodedJWT decoded = jwtTokenService.validateToken(token);

        String extractedEmail = jwtTokenService.extractEmail(decoded);

        assertEquals("extract-me@email.com", extractedEmail);
    }

    private long thirtyMinutesInSeconds() {
        return 30 * 60L;
    }

    private UserDetails buildUserDetails(String email) {
        return new User(email, "password", Collections.emptyList());
    }
}